name: GSI_Build

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'ROM_URL'
        required: true
        default: 'https://hugeota.d.miui.com/21.5.31/miui_TUCANA_21.5.31_cb42ec9bed_11.0.zip'
      ZIP_NAME:
        description: 'ZIP_NAME'
        required: true
        default: 'miui_TUCANA_21.5.31_cb42ec9bed_11.0.zip'
      ROM_NAME:
        description: 'ROM_TYPE'
        required: true
        default: 'miui'
      BUILD_TYPE:
        description: 'BUILD_TYPE(AB, A, or BOTH)'
        required: true
        default: 'AB'
env:
  TZ: Asia/Shanghai
  ZZ: MIO

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: 安装组件
         run: |
            sudo -E apt-get -qq install git wget aria2 python
            pip install uncompyle6
            uncompyle6 ${{ github.workspace }}/ > ${{ github.workspace }}/demo.py

       - name: 上传发布...
         uses: ncipollo/release-action@v1.8.0
         with:
          artifacts: "${{ github.workspace }}/demo.py"
          tag: "ERDAN_${{ github.event.inputs.BUILD_TYPE }}"
          bodyFile: "${{ github.workspace }}/ErfanGSIs/output/s.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
         
            
