name: GSI_Build

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'ROM_URL'
        required: true
        default: 'https://hugeota.d.miui.com/21.5.31/miui_TUCANA_21.5.31_cb42ec9bed_11.0.zip'
      ZIP_NAME:
        description: 'ZIP_NAME'
        required: true
        default: 'miui_TUCANA_21.5.31_cb42ec9bed_11.0.zip'
      ROM_NAME:
        description: 'ROM_TYPE'
        required: true
        default: 'miui'
      BUILD_TYPE:
        description: 'BUILD_TYPE(AB, A, or BOTH)'
        required: true
        default: 'AB'
env:
  TZ: Asia/Shanghai
  ZZ: MIO

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: 安装组件
         run: |
            sudo -E apt-get -qq install git wget aria2
       
       - name: 克隆工具源码
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: 修复异常
         run: |
              cat $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: 设置运行环境
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
       
       - name: 下载ROM并制作
         run: |
              cd  $GITHUB_WORKSPACE/ErfanGSIs
              sudo bash ./url2GSI.sh -c --${{ github.event.inputs.BUILD_TYPE }} ${{ github.event.inputs.ROM_URL }} ${{ github.event.inputs.ROM_NAME }}
       
       - name: 压缩GSI 
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              ls
              mkdir final
              zip -r final/GSI.zip ./*
              echo Done > $GITHUB_WORKSPACE/ErfanGSIs/output/s.txt
       - name: 上传发布...
         uses: ncipollo/release-action@v1.8.0
         with:
          artifacts: "${{ github.workspace }}/ErfanGSIs/output/final/GSI.zip"
          tag: "ERDAN_${{ github.event.inputs.BUILD_TYPE }}"
          bodyFile: "${{ github.workspace }}/ErfanGSIs/output/s.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
         
            
